do - Add Toggle Admin/Instructor Buttons
ucsb-cs156-f23/proj-organic-f23-6pm-4 pull request #18
Opened 2023-11-26 21:34 UTC by darylou

This PR adds the ability to toggle admin and instructor statuses.  A user can only see these buttons if they are an admin.

Github Storybook Link

Admin view:
<img width="1093" alt="Screenshot 2023-11-26 at 1 34 24 PM" src="https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/assets/91851888/1bf486ef-315e-41f8-8484-3c1b3c696fe7">

User view:
<img width="785" alt="Screenshot 2023-11-26 at 1 34 35 PM" src="https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/assets/91851888/8a493e98-33c1-4240-ac0f-53b45882e343">

Closes #13

2023-11-27 19:38 UTC, chelseastoner submitted a review, later dismissed
LGTM!

2023-11-28 00:21 UTC, dayvidwang approved these changes, later dismissed

2023-11-28 00:21 UTC, dayvidwang commented on frontend/src/tests/components/Users/UsersTable.test.js
> +    test("Has the expected colum headers and content as admin user", () => {
**column** headers (nitpick)

2023-11-28 00:21 UTC, dayvidwang commented on frontend/src/main/components/Users/UsersTable.js
> +export default function UsersTable({ users, showToggleButtons = false }) {
is there currently a use case for non-admin User Table? don't need to change this, I am just wondering.

2023-11-28 00:21 UTC, dayvidwang commented on frontend/src/tests/pages/AdminUsersPage.test.js
> +    test("usertable toggle admin tests", async ()=>{
**user table** (nitpick)

2023-11-28 00:31 UTC, darylou commented on frontend/src/main/components/Users/UsersTable.js
> +export default function UsersTable({ users, showToggleButtons = false }) {
Not currently but the criteria mentions to have this field and to show different things depending on if the user is an admin or not.

2023-11-28 01:59 UTC, chelseastoner submitted a review, later dismissed
LGTM!

2023-11-28 20:23 UTC, pconrad approved these changes
LGTM

2023-11-28 20:25 UTC, pconrad requested changes
While the code LGTM, I'd like to see a dokku deployment and test on that before merging.  We need to be sure the backend is in place before we merge this and that the frontend and backend talk to each other properly.

2023-11-28 20:48 UTC, darylou commented
Rebase to get latest backend changes that were recently merged ^

2023-11-28 20:57 UTC, darylou commented
https://proj-organic-darylou-dev.dokku-08.cs.ucsb.edu

2023-11-29 19:38 UTC, pconrad requested changes
Ok, this is a perfect example of where working with legacy code is complicated.

You did everything correctly, but somehow the toggle button effects don't show up right away---you have to refresh the page.  And here's why.

Someone in the past made a bad choice.  On the `AdminUsersPage`, instead of using `useBackend` like this:

```js
 const { data: users, error: _error, status: _status } =
        useBackend(
            // Stryker disable next-line all : don't test internal caching of React Query
            ["/api/admin/users"],
            // Stryker disable next-line StringLiteral,ObjectLiteral : since "GET" is default, "" is an equivalent mutation
            { method: "GET", url: "/api/admin/users" },
            // Stryker disable next-line all
            []
        );
```

They implemented a custom hook: 

```js
    const { data: users } = useUsers();
``` 

And they implemented it badly.  In particular, they didn't handle the cache invalidation.

As a result, your code, which correctly invalidates the cache key 

```
/ Stryker disable all : hard to test for query caching
    const toggleAdminMutation = useBackendMutation(
        cellToAxiosParamsToggleAdmin,
        {},
        ["/api/admin/users"]
    );
```

Ends up having no effect!  The solution is straightforward:

1. Repace the call to `useUsers` with the call to `useBackend` outlined above.
2. You should see that the buttons now work properly without needing a page refresh.
3. Remove the file that provides the `useUsers` hook and the matching test file; just delete them.    

Hope that helps!

2023-11-30 02:38 UTC, sumitgupta314 approved these changes, later dismissed
LGTM!

2023-11-30 05:43 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // Stryker enable all
All instances of `// Stryker enable all` should be `// Stryker restore all`

Otherwise, Stryker gets turned off for the entire rest of the file.  Fixing this may reveal other stryker surviving mutations that will need to be fixed.

2023-11-30 05:43 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // Stryker enable all
see above

2023-11-30 05:44 UTC, pconrad requested changes
One issue: the `restore` vs `enable` thing with Stryker.

Once that's fixed, this is in good shape; I tested it and it works nicely!

2023-11-30 06:02 UTC, shuyiwan submitted a review, later dismissed
LGTM!

2023-11-30 06:38 UTC, shuyiwan approved these changes
LGTM!

2023-11-30 22:26 UTC, pconrad approved these changes
LGTM

2023-11-30 22:29 UTC, merged