B1.A Backend PUT operations on Course Controller for Courses, Course Staff
ucsb-cs156-f23/proj-organic-f23-6pm-4 pull request #40
Opened 2023-11-28 03:19 UTC by dayvidwang

This PR adds an update(PUT) endpoint for courses along with associated tests. This endpoint is restricted to users only if they have the ADMIN role or if they have the INSTRUCTOR role and they are listed in the course staff for the targeted course.

Closes #6

2023-11-28 18:38 UTC, darylou approved these changes, later dismissed
LGTM!

2023-11-28 20:44 UTC, pconrad requested changes
Looks good for the most part, but there is one place where the code can be greatly simplified by using the power of the Spring framework...

2023-11-28 20:44 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
> +        }
Please see: https://ucsb-cs156.github.io/topics/sql/sql_queries.html

That article was made exactly for this situation.

There's a better approach here that replaces 14 lines of code with if tests and for loops with five lines of straight line code.

2023-11-29 17:53 UTC, darylou approved these changes
LGTM!

2023-11-30 05:52 UTC, pconrad approved these changes
LGTM

2023-11-30 06:34 UTC, merged