B1.B Backend DELETE operations on Course Controller for Courses, Course Staff
ucsb-cs156-f23/proj-organic-f23-6pm-4 pull request #41
Opened 2023-11-28 03:20 UTC by dayvidwang

This PR adds a DELETE endpoint for courses along with associated tests. This endpoint is restricted to users only if they have the ADMIN role or if they have the INSTRUCTOR role and they are listed in the course staff for the targeted course.

Closes #38

2023-11-28 18:37 UTC, darylou approved these changes
LGTM!

2023-11-28 20:18 UTC, shuyiwan approved these changes
LGTM!

2023-11-28 20:46 UTC, pconrad requested changes
Same issue as the other PR: 

https://ucsb-cs156.github.io/topics/sql/sql_queries.html

2023-11-28 20:46 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
> +        }
Please see: https://ucsb-cs156.github.io/topics/sql/sql_queries.html for a better way to do this

2023-11-29 17:52 UTC, darylou approved these changes
LGTM!

2023-11-30 06:35 UTC, pconrad approved these changes
LGTM

2023-11-30 06:35 UTC, merged