cs - Issue #11/F1: Created Schools Form
ucsb-cs156-f23/proj-organic-f23-6pm-4 pull request #48
Opened 2023-11-28 22:44 UTC by chelseastoner

This PR adds a form for schools with corresponding tests

Closes #26

2023-11-29 03:50 UTC, darylou requested changes

2023-11-29 03:50 UTC, darylou commented on frontend/src/stories/components/School/SchoolForm.stories.js
Not sure what happened but this file should remain the same and there should be a new folder called School with SchoolForm.stories.js

2023-11-29 05:22 UTC, darylou approved these changes
LGTM!

2023-11-30 22:27 UTC, pconrad approved these changes
LGTM

2023-11-30 22:29 UTC, merged